[project]
name = "rib-test-broker-seed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=40.1.2",
    "pandas>=2.3.3",
]
